# Generated by Django 5.0 on 2026-04-09 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mcu_id', models.CharField(max_length=120)),
                ('device_id', models.CharField(max_length=120)),
                ('ts', models.DateTimeField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('readings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'device_readings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceReadingLatest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mcu_id', models.CharField(max_length=120)),
                ('device_id', models.CharField(max_length=120)),
                ('ts', models.DateTimeField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('readings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'device_readings_latest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mcu_id', models.CharField(max_length=120)),
                ('device_id', models.CharField(max_length=120)),
                ('device_type', models.CharField(max_length=40)),
                ('metric_key', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(default='online', max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'field_devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Microcontroller',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mcu_id', models.CharField(max_length=120)),
                ('protocol', models.CharField(blank=True, max_length=30, null=True)),
                ('firmware', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(default='online', max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'microcontrollers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('secret_key_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('pipe_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('start_lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('end_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_lat', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
            options={
                'db_table': 'pipes',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='FlowMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pipe')),
            ],
            options={
                'db_table': 'flow_meters',
            },
        ),
        migrations.CreateModel(
            name='PressureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pipe')),
            ],
            options={
                'db_table': 'pressure_sensors',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'technicians',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.technician')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('team_size', models.CharField(blank=True, max_length=20, null=True)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('gateway_id', models.CharField(blank=True, max_length=100, null=True)),
                ('devices', models.JSONField(blank=True, default=list)),
                ('invite_emails', models.JSONField(blank=True, default=list)),
                ('threshold_soil_moisture', models.JSONField(blank=True, default=list)),
                ('threshold_ph', models.JSONField(blank=True, default=list)),
                ('threshold_pressure', models.JSONField(blank=True, default=list)),
                ('notifications', models.JSONField(blank=True, default=list)),
                ('demand_forecasting_plants', models.JSONField(blank=True, default=list)),
                ('demand_forecasting_systems', models.JSONField(blank=True, default=list)),
                ('layout_polygon', models.JSONField(blank=True, default=list)),
                ('layout_area_m2', models.FloatField(blank=True, default=0, null=True)),
                ('layout_notes', models.TextField(blank=True, null=True)),
                ('layout_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('layout_status', models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('layout_job_error', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
        migrations.AddField(
            model_name='pipe',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipes', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_id', models.CharField(db_index=True, max_length=100)),
                ('incident_type', models.CharField(db_index=True, max_length=60)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('recovering', 'Recovering'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('detected_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=220)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.workspace')),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('firmware', models.CharField(blank=True, max_length=50, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='core.workspace')),
            ],
            options={
                'db_table': 'gateways',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.workspace')),
            ],
            options={
                'db_table': 'workspace_invites',
            },
        ),
        migrations.CreateModel(
            name='PipeSpecification',
            fields=[
                ('section', models.OneToOneField(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pipespec', serialize=False, to='core.pipe')),
                ('material', models.TextField()),
                ('pipe_category', models.TextField()),
                ('pressure_class', models.TextField(blank=True, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nominal_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('flowmeter', models.ForeignKey(blank=True, db_column='flowmeter_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.flowmeter')),
                ('sensor', models.ForeignKey(blank=True, db_column='sensor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pressuresensor')),
            ],
            options={
                'db_table': 'pipe_specs',
            },
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('workspace', 'gateway_id', 'incident_type'), name='uniq_open_incident_per_type'),
        ),
    ]
