# Generated by Django 5.0 on 2026-04-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='layout',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
