# Generated by Django 5.0 on 2026-02-04 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('start_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pipes',
            },
        ),
        migrations.CreateModel(
            name='PipeSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('pressure_class', models.CharField(max_length=50)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pipe_category', models.CharField(max_length=100)),
                ('water_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pipe_specifications',
            },
        ),
        migrations.CreateModel(
            name='FlowMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pipe')),
            ],
            options={
                'db_table': 'flow_meters',
            },
        ),
        migrations.AddField(
            model_name='pipe',
            name='pipe_specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pipespecification'),
        ),
        migrations.CreateModel(
            name='PressureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pipe')),
            ],
            options={
                'db_table': 'pressure_sensors',
            },
        ),
    ]
