# Generated by Django 5.0 on 2026-02-28 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pipe_pipespecification_flowmeter_and_more'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('team_size', models.CharField(blank=True, max_length=20, null=True)),
                ('modules', models.JSONField(default=list)),
                ('gateway_id', models.CharField(blank=True, max_length=100, null=True)),
                ('threshold_soil_moisture', models.JSONField(default=list)),
                ('threshold_ph', models.JSONField(default=list)),
                ('threshold_pressure', models.JSONField(default=list)),
                ('notifications', models.JSONField(default=list)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('firmware', models.CharField(blank=True, max_length=50, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='core.workspace')),
            ],
            options={
                'db_table': 'gateways',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.workspace')),
            ],
            options={
                'db_table': 'workspace_invites',
            },
        ),
    ]
