# Generated by Django 5.0 on 2026-04-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workspace_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipespecification',
            name='flowmeter',
        ),
        migrations.RemoveField(
            model_name='pipespecification',
            name='sensor',
        ),
    ]
