# Generated by Django 5.0 on 2026-03-03 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _safe_rename_table(apps, schema_editor, old_name, new_name):
    """Safely rename a table only if it exists."""
    with schema_editor.connection.cursor() as cursor:
        # Check if the old table exists
        cursor.execute(f"SELECT name FROM sqlite_master WHERE type='table' AND name='{old_name}'")
        if cursor.fetchone():
            # Table exists, so rename it
            cursor.execute(f"ALTER TABLE {old_name} RENAME TO {new_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pipespecification_table_workspace_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='devices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workspace',
            name='invite_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='notifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='threshold_ph',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='threshold_pressure',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='threshold_soil_moisture',
            field=models.JSONField(blank=True, default=list),
        ),
        # Handle table rename safely - only if table exists
        migrations.RunPython(
            code=lambda apps, schema_editor: _safe_rename_table(apps, schema_editor, 'pipe_specifications', 'pipe_specs'),
            reverse_code=lambda apps, schema_editor: _safe_rename_table(apps, schema_editor, 'pipe_specs', 'pipe_specifications'),
        ),
    ]
