# Generated by Django 5.0 on 2026-04-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pipespecification_flowmeter_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incident',
            name='uniq_open_incident_per_type',
        ),
        migrations.AddField(
            model_name='incident',
            name='comp_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('workspace', 'gateway_id', 'incident_type', 'comp_id'), name='uniq_open_incident_per_type_and_comp'),
        ),
    ]
