# Generated by Django 5.0 on 2026-03-03 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pipespecification_table_workspace_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='devices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workspace',
            name='invite_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='notifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='threshold_ph',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='threshold_pressure',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='threshold_soil_moisture',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterModelTable(
            name='pipespecification',
            table='pipe_specs',
        ),
    ]
