# Generated by Django 5.0 on 2026-03-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_devicereading_devicereadinglatest_fielddevice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="secret_key_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
