# Generated by Django 5.0 on 2026-03-06 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_secret_key_hash'),
        ('core', '0009_workspace_workspace_name'),
    ]

    operations = [
    ]
