# Generated by Django 5.0 on 2026-04-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_workspaceinvite_token_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipe',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='pipe_specification',
        ),
        migrations.RemoveField(
            model_name='pipespecification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pipespecification',
            name='id',
        ),
        migrations.AddField(
            model_name='pipe',
            name='pipe_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipespecification',
            name='flowmeter',
            field=models.ForeignKey(blank=True, db_column='flowmeter_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.flowmeter'),
        ),
        migrations.AddField(
            model_name='pipespecification',
            name='section',
            field=models.OneToOneField(db_column='section_id', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pipespec', serialize=False, to='core.pipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipespecification',
            name='sensor',
            field=models.ForeignKey(blank=True, db_column='sensor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pressuresensor'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='end_lat',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='start_lat',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pipespecification',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pipespecification',
            name='material',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pipespecification',
            name='nominal_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pipespecification',
            name='pipe_category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pipespecification',
            name='pressure_class',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipespecification',
            name='water_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
