# Generated by Django 5.0 on 2026-04-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_pipe_id_remove_pipe_pipe_specification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipe',
            name='created_at',
        ),
    ]
