# Generated by Django 5.0 on 2026-04-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_pipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipes', to='core.workspace'),
        ),
    ]
